# Лабораторная работа №3

In [2]:
import numpy as np

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [3]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Поменять 2 строки в матрице

In [7]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print()
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

In [8]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 37) ( 4, 58) ( 5, 14) (14, 14) (18, 23) (18, 41) (20, 34) (20, 58)
 (23, 41) (25, 55) (25, 56) (29, 64) (29, 68) (32, 43) (32, 71) (32, 76)
 (32, 78) (33, 59) (33, 88) (34, 58) (37, 58) (43, 76) (48, 72) (48, 80)
 (55, 56) (59, 88) (64, 68) (71, 78) (72, 80)]


Дан массив C; создать массив A, что np.bincount(A) == C

In [9]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


Посчитать среднее, используя плавающее окно

In [10]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(moving_average(np.arange(20), 3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

In [11]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [3]:
a = np.arange(10)
s = 3
b = []
for i in range(len(a)+1-s):
    list = []
    for j in range(s):
        list.append(a[i+j])
    b.append(list)
c = np.array(b)
print(c)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [11]:
a = np.arange(10)
a[(a>3) & (a<7)] *= -1
print(a)
print(np.negative(a))

[ 0  1  2  3 -4 -5 -6  7  8  9]
[ 0 -1 -2 -3  4  5  6 -7 -8 -9]


Посчитать ранг матрицы

In [16]:
a = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(a)
print(rank)

10


Найти наиболее частое значение в массиве

In [13]:
a = np.random.randint(0,10,50)
print(a)
print(np.bincount(a))
print(np.bincount(a).argmax())

[6 6 4 8 5 7 4 8 2 7 3 9 5 7 5 0 1 0 1 6 6 0 4 8 8 9 0 9 4 4 0 8 2 8 5 1 8
 3 0 2 8 1 8 9 7 8 9 1 0 0]
[ 8  5  3  2  5  4  4  4 10  5]
8


Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [18]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 0 0]
   [2 3 2]
   [3 1 1]]

  [[0 0 0]
   [3 2 2]
   [1 1 3]]

  [[0 0 4]
   [2 2 2]
   [1 3 2]]

  [[0 4 0]
   [2 2 4]
   [3 2 1]]

  [[4 0 1]
   [2 4 1]
   [2 1 3]]

  [[0 1 1]
   [4 1 3]
   [1 3 0]]

  [[1 1 1]
   [1 3 3]
   [3 0 2]]

  [[1 1 0]
   [3 3 2]
   [0 2 4]]]


 [[[2 3 2]
   [3 1 1]
   [3 0 0]]

  [[3 2 2]
   [1 1 3]
   [0 0 1]]

  [[2 2 2]
   [1 3 2]
   [0 1 3]]

  [[2 2 4]
   [3 2 1]
   [1 3 1]]

  [[2 4 1]
   [2 1 3]
   [3 1 2]]

  [[4 1 3]
   [1 3 0]
   [1 2 2]]

  [[1 3 3]
   [3 0 2]
   [2 2 0]]

  [[3 3 2]
   [0 2 4]
   [2 0 0]]]


 [[[3 1 1]
   [3 0 0]
   [3 1 4]]

  [[1 1 3]
   [0 0 1]
   [1 4 2]]

  [[1 3 2]
   [0 1 3]
   [4 2 1]]

  [[3 2 1]
   [1 3 1]
   [2 1 0]]

  [[2 1 3]
   [3 1 2]
   [1 0 2]]

  [[1 3 0]
   [1 2 2]
   [0 2 1]]

  [[3 0 2]
   [2 2 0]
   [2 1 2]]

  [[0 2 4]
   [2 0 0]
   [1 2 0]]]


 [[[3 0 0]
   [3 1 4]
   [0 3 0]]

  [[0 0 1]
   [1 4 2]
   [3 0 1]]

  [[0 1 3]
   [4 2 1]
   [0 1 1]]

  [[1 3 1]
   [2 1 0]
   [1 1 0]]

  [[3 1 2]
   

Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [ ]:
p, n = 5, 10


Дан массив 16x16, посчитать сумму по блокам 4x4

In [9]:
matrix = np.random.randint(10,99,(16,16))
res=matrix.copy()
res.shape=(64, 4)
res=np.sum(res, axis=1)
res.shape=(4, 4, 4)
res=np.sum(res, axis=1)
print(matrix)
print(res)

[[29 92 12 57 82 45 73 34 63 35 29 34 64 53 44 17]
 [38 36 25 58 46 67 41 33 29 88 57 55 30 95 40 55]
 [26 70 43 58 88 20 58 81 85 42 80 49 82 42 54 41]
 [14 66 53 25 87 81 70 44 95 32 73 64 34 88 93 37]
 [10 28 58 60 32 16 94 32 23 67 65 55 75 15 22 51]
 [90 73 45 16 38 54 61 15 86 10 82 25 84 44 88 38]
 [27 33 32 44 75 96 52 82 40 56 86 20 93 31 87 66]
 [96 12 15 74 65 87 70 69 63 69 68 43 97 61 59 56]
 [34 21 30 36 45 67 54 49 57 57 60 67 80 26 16 34]
 [33 83 12 14 41 97 66 58 55 63 88 94 47 55 24 37]
 [57 45 50 54 97 84 87 76 32 61 96 91 26 53 33 82]
 [31 68 52 88 62 46 91 23 77 32 16 15 57 62 59 90]
 [52 38 39 41 54 84 72 23 39 47 90 16 84 53 24 74]
 [39 96 73 71 56 69 83 88 69 68 94 85 69 61 78 91]
 [11 85 71 52 96 13 13 41 94 38 43 90 54 80 13 24]
 [76 47 65 22 96 41 43 29 10 40 34 70 39 96 89 87]]
[[ 702  950  910  869]
 [ 713  938  858  967]
 [ 708 1043  961  781]
 [ 878  901  927 1016]]


Найти n наибольших значений в массиве

In [19]:
a = np.arange(10000)
np.random.shuffle(a)
n = 5

print (a[np.argpartition(-a,n)[:n]])

[9999 9998 9997 9996 9995]


Построить прямое произведение массивов (все комбинации с каждым элементом)

In [20]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [21]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[3 4 6]


Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

In [22]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[4 3 1]
 [2 2 4]
 [1 1 3]
 [0 3 1]
 [0 0 0]
 [3 0 3]
 [4 0 3]
 [4 2 4]
 [1 3 0]
 [1 3 2]]
[[4 3 1]
 [2 2 4]
 [1 1 3]
 [0 3 1]
 [3 0 3]
 [4 0 3]
 [4 2 4]
 [1 3 0]
 [1 3 2]]


Преобразовать вектор чисел в матрицу бинарных представлений

In [23]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


Дан двумерный массив. Найти все различные строки

In [24]:
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [25]:
np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j', A, B)    # np.outer(A, B)

ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.