<center>Московский Авиационный Институт</center>
<center>(Национальный Исследовательский Университет)</center>
<br>
<br>
<br>
<center>Кафедра: 806 «Вычислительная математика и программирование»</center>
<center>Институт: «Информационные технологии и прикладная математика»</center>
<center>Дисциплина: «Разработка ПО для высокопроизводительных систем»</center>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<center>Лабораторная работа №1.</center>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div style="text-align: right"> Группа М80-103М-20 </div>
<div style="text-align: right"> Студент Степанов Тимур Петрович </div>
<div style="text-align: right"> Поповкин А.В. </div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<center>Москва</center>
<center>2020</center>
<hr>

# Лабораторная работа №1

Импортировать NumPy под именем np

In [2]:
import numpy as np

Напечатать версию и конфигурацию

In [2]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/timur/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/timur/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/timur/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [8]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Создать вектор размера 10, заполненный единицами

In [5]:
x = np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Создать вектор размера 10, заполненный числом 2.5

In [6]:
x = np.full(10, 2.5)
print(x)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


Как получить документацию о функции numpy.add из командной строки?

In [9]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Создать вектор со значениями от 10 до 49

In [10]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Развернуть вектор (первый становится последним)

In [4]:
x = np.arange(50)
print(np.flip(x,0))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [15]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [13]:
x = np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4], dtype=int64),)


Создать массив 3x3x3 со случайными значениями

In [11]:
x = np.random.random((3,3,3))
print(x)

[[[0.18415146 0.84534088 0.78460399]
  [0.23935395 0.55725916 0.92455104]
  [0.00767325 0.17845063 0.1182321 ]]

 [[0.37345067 0.140377   0.93854044]
  [0.92452018 0.32560941 0.06408617]
  [0.04622488 0.74721952 0.49900266]]

 [[0.30787584 0.46394356 0.53990831]
  [0.47973152 0.66212443 0.02217489]
  [0.28761739 0.21326308 0.00247515]]]


In [10]:
np.random.rand(3,3,3)

array([[[0.23428738, 0.81385911, 0.44065774],
        [0.7470331 , 0.30734851, 0.93170668],
        [0.03428709, 0.82752842, 0.08846598]],

       [[0.51674414, 0.55304767, 0.54534648],
        [0.02508858, 0.58098439, 0.71647528],
        [0.20357118, 0.90274729, 0.53805436]],

       [[0.18241538, 0.40052605, 0.07032593],
        [0.19270569, 0.74735128, 0.14999559],
        [0.95976687, 0.22548508, 0.82379216]]])

Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [16]:
x = np.random.random((10,10))
x_min, x_max = x.min(), x.max()
print(x_min, x_max)

0.03088454442766464 0.9996564005607527


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [7]:
x = np.random.random(30)
m = x.mean()
s = np.mean(x)
print(m, ' ', s)

0.5034298045200455   0.5034298045200455


Создать матрицу с 0 внутри, и 1 на границах

In [18]:
x = np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [20]:
x = np.diag(np.arange(1, 5), k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Создать 8x8 матрицу и заполнить её в шахматном порядке

In [21]:
x = np.zeros((8,8), dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [22]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [23]:
x = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
