# Лабораторная работа №2

In [1]:
import numpy as np

Перемножить матрицы 5x3 и 3x2

In [2]:
x = np.dot(np.ones((5,3)), np.ones((3,2)))
print(x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
x = np.arange(11)
x[(3 < x) & (x <= 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


Создать 5x5 матрицу со значениями в строках от 0 до 4

In [4]:
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Есть генератор, сделать с его помощью массив

In [5]:
def generate():
    for x in range(10):
        yield x
x = np.fromiter(generate(),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [6]:
x = np.linspace(0,1,12)[1:-1]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Отсортировать вектор

In [7]:
x = np.random.random(10)
x.sort()
print(x)

[0.24415261 0.28889521 0.31582309 0.33678411 0.49395878 0.52239705
 0.70523283 0.76236459 0.7774112  0.92400232]


Проверить, одинаковы ли 2 numpy массива

In [8]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
isequal = np.allclose(A,B)
print(isequal)

False


Сделать массив неизменяемым

In [9]:
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1

ValueError: assignment destination is read-only

Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [10]:
z = np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.hypot(x, y)
fi = np.arctan2(y,x)
print(r)
print(fi)

[0.60419436 0.68819238 0.60255628 0.48155873 0.78402805 0.59875237
 1.18260862 0.95297849 0.98710225 0.97036225]
[0.27272838 0.12744793 0.90074647 0.08022497 0.21230165 0.51505081
 0.68956328 1.21295079 1.5623856  0.15473011]


Заменить максимальный элемент на ноль

In [11]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.4374807  0.31544996 0.         0.77476758 0.26715128 0.1132344
 0.46910777 0.50567527 0.31866648 0.12828389]


Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [34]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(c)
print(np.linalg.det(c))

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.1636371179666


Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [14]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


Найти ближайшее к заданному значению число в заданном массиве

In [16]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

99


Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [17]:
 Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-17-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [18]:
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.31344828 0.25368243 0.38410521 0.84577097 0.55507098
  0.58917547 0.36825076 0.32172096 0.12943841]
 [0.31344828 0.         0.18002308 0.54357761 0.63472021 0.58592134
  0.28130607 0.57245914 0.29717799 0.43705669]
 [0.25368243 0.18002308 0.         0.36784799 0.59305283 0.4142902
  0.38287871 0.60014416 0.12326229 0.34391569]
 [0.38410521 0.54357761 0.36784799 0.         0.75143597 0.24750177
  0.72797706 0.71575944 0.28244614 0.33320107]
 [0.84577097 0.63472021 0.59305283 0.75143597 0.         0.5546801
  0.46407977 1.18618069 0.54512221 0.91788234]
 [0.55507098 0.58592134 0.4142902  0.24750177 0.5546801  0.
  0.67412947 0.91714071 0.29118943 0.54753869]
 [0.58917547 0.28130607 0.38287871 0.72797706 0.46407977 0.67412947
  0.         0.84200928 0.44567194 0.70615307]
 [0.36825076 0.57245914 0.60014416 0.71575944 1.18618069 0.91714071
  0.84200928 0.         0.68723212 0.38279888]
 [0.32172096 0.29717799 0.12326229 0.28244614 0.54512221 0.29118943
  0.44567194 0.6872321

Преобразовать массив из float в int

In [19]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Каков эквивалент функции enumerate для numpy массивов?

In [21]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


Сформировать 2D массив с распределением Гаусса

In [22]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.hypot(X, Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu) ** 2 / (2.0 * sigma ** 2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

Случайно расположить p элементов в 2D массив

In [23]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Отнять среднее из каждой строки в матрице

In [24]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.36724173 -0.27394402  0.22355174 -0.06868551  0.20670985 -0.36163833
   0.33862978 -0.24892976  0.01429714 -0.19723262]
 [-0.30990841 -0.25089662  0.29668423 -0.04206111 -0.06511663 -0.09775542
  -0.05076016  0.23844756  0.024112    0.25725456]
 [-0.62286304  0.12987102  0.20701783  0.20186666  0.17617337 -0.30484784
   0.1581108  -0.15351428  0.25715355 -0.04896809]
 [ 0.46877498  0.45571668 -0.09666992 -0.1213552   0.08337184  0.05730512
  -0.14273507 -0.08326182 -0.45194316 -0.16920345]
 [-0.06767348 -0.07160462  0.25175068 -0.16030278 -0.32531064 -0.29693926
   0.08110002  0.44768441  0.29726768 -0.155972  ]]


Отсортировать матрицу по n-ому столбцу

In [25]:
Z = np.random.randint(0,10,(3,3))
n = 1  # Нумерация с нуля
print(Z)
print(Z[Z[:,n].argsort()])

[[4 7 6]
 [4 8 1]
 [4 6 5]]
[[4 6 5]
 [4 7 6]
 [4 8 1]]


Определить, есть ли в 2D массиве нулевые столбцы

In [26]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

[[2 1 2 2 0 2 1 0 0 2]
 [0 1 2 0 1 2 1 0 0 2]
 [2 0 2 2 0 0 1 2 2 2]]
False


Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [27]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 1. 4. 3. 2. 3. 4. 2. 5. 3.]


Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [28]:
w,h = 16,16
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


Дан четырехмерный массив, посчитать сумму по последним двум осям

In [33]:
A = np.random.randint(0,10, (3,4,3,4))
print(A)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[[[9 9 5 1]
   [2 9 1 1]
   [9 3 4 0]]

  [[3 7 2 9]
   [8 0 4 8]
   [8 8 6 1]]

  [[4 9 4 8]
   [3 4 0 3]
   [9 3 7 3]]

  [[2 2 0 7]
   [0 9 3 1]
   [0 1 6 1]]]


 [[[8 0 0 8]
   [9 4 3 1]
   [4 8 1 7]]

  [[3 3 6 2]
   [7 6 9 1]
   [6 5 2 2]]

  [[2 7 8 8]
   [3 8 2 2]
   [0 7 2 2]]

  [[3 6 1 0]
   [0 1 9 7]
   [2 7 9 0]]]


 [[[2 5 1 2]
   [9 2 4 7]
   [7 6 9 4]]

  [[0 0 7 9]
   [8 3 6 0]
   [7 6 3 2]]

  [[0 0 6 8]
   [4 2 6 1]
   [6 0 4 6]]

  [[4 0 3 2]
   [6 9 4 3]
   [9 2 6 7]]]]
[[53 64 57 32]
 [53 52 51 45]
 [58 51 43 55]]


Найти диагональные элементы произведения матриц

In [32]:
A = np.ones((3,3))
B = np.ones((3,3))
np.diag(np.dot(A, B))

array([3., 3., 3.])