# Лабораторная работа №3

In [2]:
import numpy as np

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [3]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Поменять 2 строки в матрице

In [7]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print()
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

In [8]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 37) ( 4, 58) ( 5, 14) (14, 14) (18, 23) (18, 41) (20, 34) (20, 58)
 (23, 41) (25, 55) (25, 56) (29, 64) (29, 68) (32, 43) (32, 71) (32, 76)
 (32, 78) (33, 59) (33, 88) (34, 58) (37, 58) (43, 76) (48, 72) (48, 80)
 (55, 56) (59, 88) (64, 68) (71, 78) (72, 80)]


Дан массив C; создать массив A, что np.bincount(A) == C

In [9]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


Посчитать среднее, используя плавающее окно

In [10]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(moving_average(np.arange(20), 3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

In [3]:
a = np.arange(10)
s = 3
b = []
for i in range(len(a)+1-s):
    list = []
    for j in range(s):
        list.append(a[i+j])
    b.append(list)
c = np.array(b)
print(c)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [11]:
a = np.arange(10)
a[(a>3) & (a<7)] *= -1
print(a)
print(np.negative(a))

[ 0  1  2  3 -4 -5 -6  7  8  9]
[ 0 -1 -2 -3  4  5  6 -7 -8 -9]


Посчитать ранг матрицы

In [16]:
a = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(a)
print(rank)

10


Найти наиболее частое значение в массиве

In [13]:
a = np.random.randint(0,10,50)
print(a)
print(np.bincount(a))
print(np.bincount(a).argmax())

[6 6 4 8 5 7 4 8 2 7 3 9 5 7 5 0 1 0 1 6 6 0 4 8 8 9 0 9 4 4 0 8 2 8 5 1 8
 3 0 2 8 1 8 9 7 8 9 1 0 0]
[ 8  5  3  2  5  4  4  4 10  5]
8


Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [26]:
n = 5
a = np.random.randint(0,5,(n,n))
s = 3
b = []
print(a)
for i in range((n-2)):
    for j in range(n-2):
        temp = a[i:i+s,j:j+s]
        b.append(temp)
c = np.array(b)
print(c)


[[4 4 2 3 4]
 [3 4 1 4 1]
 [2 1 0 0 4]
 [0 2 4 3 1]
 [4 2 0 0 3]]
[[[4 4 2]
  [3 4 1]
  [2 1 0]]

 [[4 2 3]
  [4 1 4]
  [1 0 0]]

 [[2 3 4]
  [1 4 1]
  [0 0 4]]

 [[3 4 1]
  [2 1 0]
  [0 2 4]]

 [[4 1 4]
  [1 0 0]
  [2 4 3]]

 [[1 4 1]
  [0 0 4]
  [4 3 1]]

 [[2 1 0]
  [0 2 4]
  [4 2 0]]

 [[1 0 0]
  [2 4 3]
  [2 0 0]]

 [[0 0 4]
  [4 3 1]
  [0 0 3]]]


Дан массив 16x16, посчитать сумму по блокам 4x4

In [90]:
matrix = np.random.randint(10,99,(16,16))
res=matrix.copy()
res.shape=(64, 4)
res=np.sum(res, axis=1)
res.shape=(4, 4, 4)
res=np.sum(res, axis=1)
print(matrix)
print(res)

[[16 13 92 44 44 45 65 95 40 12 90 17 10 64 37 32]
 [91 56 90 37 60 46 26 84 51 48 36 65 91 54 73 36]
 [28 10 53 52 76 34 65 72 81 78 31 64 72 95 75 36]
 [13 71 78 79 75 59 37 86 93 86 27 27 51 78 48 63]
 [31 89 60 47 30 51 64 86 15 19 32 55 48 62 48 73]
 [37 57 89 76 49 24 63 85 85 75 23 77 37 78 23 22]
 [96 87 67 36 32 97 95 34 74 84 86 56 23 72 45 59]
 [69 68 35 72 56 74 86 55 45 98 22 27 90 83 55 18]
 [37 75 87 25 78 94 27 34 74 31 80 29 98 48 27 98]
 [58 11 29 61 66 93 74 24 21 84 43 25 67 91 44 69]
 [29 30 35 63 59 47 45 15 60 50 71 55 95 52 87 98]
 [88 42 32 29 12 33 43 29 50 15 37 39 70 36 26 23]
 [22 98 97 49 36 80 35 81 65 46 12 20 37 18 69 48]
 [68 65 18 20 49 61 73 98 12 46 84 92 21 95 80 37]
 [79 24 88 23 12 73 66 80 65 72 23 60 76 55 47 53]
 [26 34 47 34 59 65 83 42 23 67 68 51 27 93 24 62]]
[[ 823  969  846  915]
 [1016  981  873  836]
 [ 731  773  764 1029]
 [ 792  993  806  842]]


Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [28]:
p, n = 5, 10
a_vector = np.ones((p,n,))
a_matrix = np.ones((p,n,n))
print(np.einsum('ijk,ik->k',a_matrix, a_vector))

[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


Найти n наибольших значений в массиве

In [91]:
a = np.random.randint(0, 100, (5, 5))
n =3
b = a.flatten()
b.sort()
print(b[-n:])

[89 90 92]


Построить прямое произведение массивов (все комбинации с каждым элементом)

In [101]:
def all_mult(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(all_mult(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [21]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[3 4 6]


Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

In [22]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[4 3 1]
 [2 2 4]
 [1 1 3]
 [0 3 1]
 [0 0 0]
 [3 0 3]
 [4 0 3]
 [4 2 4]
 [1 3 0]
 [1 3 2]]
[[4 3 1]
 [2 2 4]
 [1 1 3]
 [0 3 1]
 [3 0 3]
 [4 0 3]
 [4 2 4]
 [1 3 0]
 [1 3 2]]


Преобразовать вектор чисел в матрицу бинарных представлений

In [23]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


Дан двумерный массив. Найти все различные строки

In [120]:
Z = np.random.randint(0, 2, (6,3))
print(Z)
all_1 = list()
for i in range(len(Z)):
    list_1 = list(Z[i,])
    m=0
    for i in all_1:
        if i == list_1:
            m += 1
    if m == 0:
        all_1.append(list_1)
print("razlichnie stroki", end="\n")
print(np.array(all_1))

[[0 0 0]
 [1 1 0]
 [0 0 1]
 [1 1 1]
 [0 0 0]
 [0 1 0]]
razlichnie stroki
[[0 0 0]
 [1 1 0]
 [0 0 1]
 [1 1 1]
 [0 1 0]]


In [109]:
arr1 = np.random.randint(0,10,5)
arr2 = np.random.randint(0,10,5)

print(arr1)
print(arr2)
print("sum", end="\n")
print(np.einsum('i->',arr1))
print(np.sum(arr1))
print("multiplication", end="\n")
print(np.einsum('i,i->i',arr1, arr2))
print(np.multiply(arr1, arr2))
print("inner", end="\n")
print(np.einsum('i,i->', arr1, arr2))
print(np.inner(arr1,arr2))
print("outer", end="\n")
print(np.einsum('i,j->ij', arr1, arr2))
print(np.outer(arr1,arr2))

[5 3 9 2 4]
[1 6 9 7 8]
sum
23
23
multiplication
[ 5 18 81 14 32]
[ 5 18 81 14 32]
inner
150
150
outer
[[ 5 30 45 35 40]
 [ 3 18 27 21 24]
 [ 9 54 81 63 72]
 [ 2 12 18 14 16]
 [ 4 24 36 28 32]]
[[ 5 30 45 35 40]
 [ 3 18 27 21 24]
 [ 9 54 81 63 72]
 [ 2 12 18 14 16]
 [ 4 24 36 28 32]]
